import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      textColor: {
        "sudo-black": "#121212",
        "sudo-blue": "#9bcdff",
        "sudo-dark-shade-0": "#0d0d12",
        "sudo-dark-shade-4": "#14141b",
        "sudo-dark-shade-4-tp": "rgba(20, 20, 27, 0.6)",
        "sudo-dark-shade-8": "#1b1b25",
        "sudo-dark-shade-16": "#36364b",
        "sudo-dark-shade-24": "#36364b",
        "sudo-dark-shade-50": "#9292a5",
        "sudo-dark-shade-70": "#b7b7c9",
        "sudo-dark-shade-80": "#cacadb",
        "sudo-dark-shade-90": "#dcdced",
        "sudo-dark-shade-100": "#eeeeff",
        "sudo-pink": "#ff9bff",
        "sudo-purple": "#b9b9ff",
        "sudo-purple-light": "rgba(185, 185, 255, 0.16)",
        "white-o50": "rgba(255, 255, 255, 0.5)",
        "white-o75": "rgba(255, 255, 255, 0.75)",
      },
      colors: {
        "sudo-purple": "hsl(var(--sudo-purple))",
        "sudo-black": "#121212",
        "sudo-blue": "#9bcdff",
        "sudo-dark-shade-0": "#0d0d12",
        "sudo-dark-shade-4": "#14141b",
        "sudo-dark-shade-4-tp": "rgba(20, 20, 27, 0.6)",
        "sudo-dark-shade-8": "#1b1b25",
        "sudo-dark-shade-16": "#36364b",
        "sudo-dark-shade-24": "#36364b",
        "sudo-dark-shade-50": "#9292a5",
        "sudo-dark-shade-70": "#b7b7c9",
        "sudo-dark-shade-80": "#cacadb",
        "sudo-dark-shade-90": "#dcdced",
        "sudo-dark-shade-100": "#eeeeff",
        "sudo-pink": "#ff9bff",
        "sudo-purple-dark": "#8181cf",
        "sudo-purple-dark1": "#292938",
        "sudo-purple-dark2": "#14141B",
        "sudo-purple-dark2-tp": "#14141ba5",
        "sudo-purple-light": "rgba(185, 185, 255, 0.16)",
        "sudo-secondary-light": "#ffffff14",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderColor: {
        DEFAULT: "hsl(var(--border))",
      },
    },
  },
} satisfies Config;
